### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by DrakaSAN** [cozy/ACH#129]
Trying to install via npm currently fails:

```sh
$ npm i -g cozy-ach
npm ERR! Cannot read properties of null (reading 'edgesOut')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-06-23T07_31_16_080Z-debug-0.log
```

Logfile:

```
0 verbose cli /home/user/.nvs/node/16.13.1/x64/bin/node /home/user/.nvs/default/bin/npm
1 info using npm@8.12.2
2 info using node@v16.13.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/user/.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/home/user/.nvs/node/16.13.1/x64/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 12ms
18 timing npm:load:configload Completed in 13ms
19 timing npm:load:mkdirpcache Completed in 2ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm i cozy-ach
22 verbose argv "i" "--global" "cozy-ach"
23 timing npm:load:setTitle Completed in 1ms
24 timing config:load:flatten Completed in 3ms
25 timing npm:load:display Completed in 6ms
26 verbose logfile logs-max:10 dir:/home/user/.npm/_logs
27 verbose logfile /home/user/.npm/_logs/2022-06-23T07_31_16_080Z-debug-0.log
28 timing npm:load:logFile Completed in 6ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 29ms
32 timing arborist:ctor Completed in 2ms
33 silly logfile start cleaning logs, removing 2 files
34 timing idealTree:init Completed in 8ms
35 timing idealTree:userRequests Completed in 3ms
36 silly idealTree buildDeps
37 silly fetch manifest cozy-ach@*
38 silly logfile done cleaning log files
39 http fetch GET 200 https://registry.npmjs.org/cozy-ach 303ms (cache revalidated)
40 silly placeDep ROOT cozy-ach@1.45.0 OK for:  want: *
41 silly fetch manifest babel-runtime@6.26.0
42 silly fetch manifest btoa@1.2.1
43 silly fetch manifest colors@^1.3.3
44 silly fetch manifest commander@^2.19.0
45 silly fetch manifest core-js@3.0.0
46 silly fetch manifest cozy-client@^29.1.3
47 silly fetch manifest cozy-client-js@^0.15.0
48 silly fetch manifest cozy-device-helper@^2.1.0
49 silly fetch manifest cozy-doctypes@1.39.0
50 silly fetch manifest cozy-flags@^2.8.7
51 silly fetch manifest date-fns@1.30.1
52 silly fetch manifest directory-tree@^2.2.1
53 silly fetch manifest dummy-json@^2.0.0
54 silly fetch manifest es6-promise-pool@^2.5.0
55 silly fetch manifest faker@^5.5.3
56 silly fetch manifest isomorphic-fetch@2.2.1
57 silly fetch manifest jest-diff@^24.5.0
58 silly fetch manifest jsonwebtoken@^8.5.1
59 silly fetch manifest lodash@^4.17.11
60 silly fetch manifest opn@^5.1.0
61 silly fetch manifest progress@^2.0.3
62 silly fetch manifest regenerator-runtime@0.11.0
63 silly fetch manifest request@^2.88.2
64 silly fetch manifest server-destroy@^1.0.1
65 silly fetch manifest timezone@^1.0.22
66 http fetch GET 200 https://registry.npmjs.org/btoa 117ms (cache revalidated)
67 http fetch GET 200 https://registry.npmjs.org/faker 135ms (cache revalidated)
68 http fetch GET 200 https://registry.npmjs.org/commander 167ms (cache revalidated)
69 http fetch GET 200 https://registry.npmjs.org/jest-diff 163ms (cache revalidated)
70 http fetch GET 200 https://registry.npmjs.org/colors 179ms (cache revalidated)
71 http fetch GET 200 https://registry.npmjs.org/babel-runtime 192ms (cache revalidated)
72 http fetch GET 200 https://registry.npmjs.org/isomorphic-fetch 185ms (cache revalidated)
73 http fetch GET 200 https://registry.npmjs.org/core-js 196ms (cache revalidated)
74 http fetch GET 200 https://registry.npmjs.org/jsonwebtoken 191ms (cache revalidated)
75 http fetch GET 200 https://registry.npmjs.org/lodash 192ms (cache revalidated)
76 http fetch GET 200 https://registry.npmjs.org/date-fns 199ms (cache revalidated)
77 http fetch GET 200 https://registry.npmjs.org/regenerator-runtime 209ms (cache revalidated)
78 http fetch GET 200 https://registry.npmjs.org/opn 212ms (cache revalidated)
79 http fetch GET 200 https://registry.npmjs.org/progress 214ms (cache revalidated)
80 http fetch GET 200 https://registry.npmjs.org/timezone 210ms (cache revalidated)
81 http fetch GET 200 https://registry.npmjs.org/request 214ms (cache revalidated)
82 http fetch GET 200 https://registry.npmjs.org/server-destroy 226ms (cache revalidated)
83 http fetch GET 200 https://registry.npmjs.org/cozy-device-helper 337ms (cache revalidated)
84 http fetch GET 200 https://registry.npmjs.org/cozy-flags 339ms (cache revalidated)
85 http fetch GET 200 https://registry.npmjs.org/cozy-client 791ms (cache revalidated)
86 http fetch GET 200 https://registry.npmjs.org/dummy-json 803ms (cache revalidated)
87 http fetch GET 200 https://registry.npmjs.org/directory-tree 817ms (cache revalidated)
88 http fetch GET 200 https://registry.npmjs.org/cozy-client-js 825ms (cache revalidated)
89 http fetch GET 200 https://registry.npmjs.org/cozy-doctypes 832ms (cache revalidated)
90 http fetch GET 200 https://registry.npmjs.org/es6-promise-pool 832ms (cache revalidated)
91 timing idealTree:#root Completed in 1166ms
92 silly fetch manifest cozy-logger@>1.7.0
93 http fetch GET 200 https://registry.npmjs.org/cozy-logger 680ms (cache revalidated)
94 silly fetch manifest cozy-ui@>34.0.0
95 http fetch GET 200 https://registry.npmjs.org/cozy-ui 251ms (cache revalidated)
96 silly fetch manifest @material-ui/core@>=4.12
97 http fetch GET 200 https://registry.npmjs.org/@material-ui%2fcore 62ms (cache revalidated)
98 silly fetch manifest @types/react@^16.8.6 || ^17.0.0
99 http fetch GET 200 https://registry.npmjs.org/@types%2freact 53ms (cache revalidated)
100 silly fetch manifest react@^16.8.0 || ^17.0.0
101 http fetch GET 200 https://registry.npmjs.org/react 58ms (cache revalidated)
102 silly fetch manifest react-dom@^16.8.0 || ^17.0.0
103 http fetch GET 200 https://registry.npmjs.org/react-dom 41ms (cache revalidated)
104 silly fetch manifest cozy-doctypes@^1.69.0
105 silly fetch manifest cozy-harvest-lib@^6.7.3
106 http fetch GET 200 https://registry.npmjs.org/cozy-harvest-lib 1294ms (cache updated)
107 silly fetch manifest @babel/runtime@>=7.12.5
108 http fetch GET 200 https://registry.npmjs.org/@babel%2fruntime 48ms (cache revalidated)
109 silly fetch manifest cozy-keys-lib@>=3.7.0
110 http fetch GET 200 https://registry.npmjs.org/cozy-keys-lib 696ms (cache revalidated)
111 silly fetch manifest cozy-client@^16.10.2
112 silly fetch manifest cozy-ui@^42.3.0
113 silly fetch manifest cozy-ui@^34.0.0
114 silly fetch manifest react@^16.8.3
115 silly fetch manifest @material-ui/core@3.9.4
116 silly fetch manifest react-dom@^16.9.0
117 silly fetch manifest cozy-client@^13.4.0
118 silly fetch manifest cozy-device-helper@^1.7.5
119 silly fetch manifest cozy-device-helper@1.10.0
120 silly fetch manifest cozy-stack-client@>=13.15.1
121 http fetch GET 200 https://registry.npmjs.org/cozy-stack-client 707ms (cache revalidated)
122 silly fetch manifest cozy-flags@^2.6.0
123 silly fetch manifest piwik-react-router@^0.8.2
124 http fetch GET 200 https://registry.npmjs.org/piwik-react-router 263ms (cache revalidated)
125 silly fetch manifest history@^3.0.0 || ^4.0.0
126 http fetch GET 200 https://registry.npmjs.org/history 33ms (cache revalidated)
127 silly fetch manifest puppeteer@1.20.0
128 http fetch GET 200 https://registry.npmjs.org/puppeteer 55ms (cache revalidated)
129 silly fetch manifest react@^16.8.6
130 silly fetch manifest react-dom@^16.8.6
131 silly fetch manifest cozy-device-helper@1.7.5
132 silly fetch manifest preact@^8.3.1
133 http fetch GET 200 https://registry.npmjs.org/preact 54ms (cache revalidated)
134 silly fetch manifest preact-portal@^1.1.3
135 http fetch GET 200 https://registry.npmjs.org/preact-portal 212ms (cache revalidated)
136 silly fetch manifest @babel/runtime@^7.3.4
137 silly fetch manifest cozy-flags@>2.8.6
138 silly fetch manifest cozy-client@>=20.0.0
139 silly fetch manifest cozy-device-helper@>=2.1.0
140 silly fetch manifest react@^16.12.0
141 silly fetch manifest react@17.0.2
142 silly fetch manifest cozy-realtime@>=3.12.2
143 http fetch GET 200 https://registry.npmjs.org/cozy-realtime 677ms (cache revalidated)
144 silly fetch manifest leaflet@^1.7.1
145 http fetch GET 200 https://registry.npmjs.org/leaflet 36ms (cache revalidated)
146 silly fetch manifest react-router-dom@^5.0.1
147 http fetch GET 200 https://registry.npmjs.org/react-router-dom 29ms (cache revalidated)
148 timing idealTree Completed in 6931ms
149 timing command:i Completed in 6954ms
150 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
150 verbose stack     at Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1354:38)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1362:11)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1402:19)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1362:11)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1362:11)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1402:19)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1404:9)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1362:11)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1362:11)
150 verbose stack     at async Arborist.[loadPeerSet] (/home/user/.nvs/node/16.13.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1362:11)
151 verbose cwd /home/user
152 verbose Linux 4.19.0-20-amd64
153 verbose node v16.13.1
154 verbose npm  v8.12.2
155 error Cannot read properties of null (reading 'edgesOut')
156 verbose exit 1
157 timing npm Completed in 7115ms
158 verbose unfinished npm timer reify 1655969476240
159 verbose unfinished npm timer reify:loadTrees 1655969476258
160 verbose unfinished npm timer idealTree:buildDeps 1655969476270
161 verbose unfinished npm timer idealTree:node_modules/cozy-ach 1655969477437
162 verbose code 1
163 error A complete log of this run can be found in:
163 error     /home/user/.npm/_logs/2022-06-23T07_31_16_080Z-debug-0.log
```

`yarn global` seems to not be supported anymore:
- https://github.com/yarnpkg/berry/issues/821
- https://github.com/yarnpkg/berry/pull/903
- https://github.com/yarnpkg/berry/pull/917

The alternative, `yarn dlx`, crash on a misconfigured dependency:

```sh
$ yarn dlx cozy-ach
➤ YN0000: ┌ Resolution step
➤ YN0061: │ core-js@npm:3.0.0 is deprecated: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ uuid@npm:3.2.1 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide babel-polyfill (p32403), requested by cozy-client-js
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide cozy-logger (p55cfb), requested by cozy-client
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide cozy-ui (p03e73), requested by cozy-client
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide react (p6dc36), requested by cozy-client
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide react (pc4ad2), requested by cozy-flags
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide react-native (p37378), requested by cozy-client
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide react-native-google-safetynet (pf3347), requested by cozy-client
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide react-native-inappbrowser-reborn (p7d919), requested by cozy-client
➤ YN0002: │ cozy-ach@npm:1.45.0 doesn't provide react-native-ios11-devicecheck (pd960b), requested by cozy-client
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 3s 375ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ webidl-conversions@npm:3.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ whatwg-fetch@npm:3.6.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ whatwg-url@npm:5.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ which-boxed-primitive@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wordwrap@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 7s 974ms
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 207ms
➤ YN0000: Done with warnings in 12s 631ms

/tmp/xfs-2d1f9af8/dlx-16215/.pnp.cjs:11000
    throw firstError;
    ^

Error: cozy-client-js tried to access btoa, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: btoa
Required by: cozy-client-js@virtual:4e5b286eaf1c1d9086ec7e4ed1240dfbcf2932bf43508f67a8470c6c6d3d2f4aaa5f2a287c30e704bca203b5247cd3db52315463c1e0329ccc616eda06849787#npm:0.15.1 (via /tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/)

Require stack:
- /tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/cozy-client.node.js
- /home/user/.yarn/berry/cache/cozy-ach-npm-1.45.0-4e5b286eaf-8.zip/node_modules/cozy-ach/libs/getClient.js
- /home/user/.yarn/berry/cache/cozy-ach-npm-1.45.0-4e5b286eaf-8.zip/node_modules/cozy-ach/libs/index.js
- /home/user/.yarn/berry/cache/cozy-ach-npm-1.45.0-4e5b286eaf-8.zip/node_modules/cozy-ach/cli.js
    at Function.require$$0.Module._resolveFilename (/tmp/xfs-2d1f9af8/dlx-16215/.pnp.cjs:10999:13)
    at Function.require$$0.Module._load (/tmp/xfs-2d1f9af8/dlx-16215/.pnp.cjs:10853:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/cozy-client.node.js:1057:18)
    at __webpack_require__ (/tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/cozy-client.node.js:20:30)
    at Object.<anonymous> (/tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/cozy-client.node.js:1921:44)
    at __webpack_require__ (/tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/cozy-client.node.js:20:30)
    at Object.<anonymous> (/tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/cozy-client.node.js:1346:15)
    at Object.<anonymous> (/tmp/xfs-2d1f9af8/dlx-16215/.yarn/__virtual__/cozy-client-js-virtual-a86f1946ce/4/home/user/.yarn/berry/cache/cozy-client-js-npm-0.15.1-139e67bfb9-8.zip/node_modules/cozy-client-js/dist/cozy-client.node.js:1726:30)
```

Is there another installation method I can try ?

**Comment by Crash--** [comment]
Hi, thanks for rising the issue. I can reproduce it with npm 8. 

In the meantime, you can install it from yarn: 
```bash
> yarn --version
1.22.18
> yarn global add cozy-ach
...
success Installed "cozy-ach@1.45.0" with binaries:
      - ACH
✨  Done in 4.94s.
```

**Comment by DrakaSAN** [comment]
As a workaround, I cloned the project and used `npm link` to have it in my executables, installing yarn 1 would have been a good idea too

Wanted to play around with cozy's code for some time now, guess it will encourage me to do so now :)

**Comment by BastLast** [comment]
hey ! just got the same issue, thx for the workarround with yarn.
